april/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^/?$', 'gpt2.views.home', name='home'),

    url(r'^regionales2010/', include('gpt2.urls', namespace='regionales2010', app_name='gpt2')),
    url(r'^cantonales2008/', include('gpt2.urls', namespace='cantonales2008', app_name='gpt2')),
    url(r'^europarl2009/', include('gpt2.urls', namespace='europarl2009', app_name='gpt2')),
    url(r'^municipales2008/', include('gpt2.urls', namespace='municipales2008', app_name='gpt2')),
    url(r'^municipales2014/', include('gpt2.urls', namespace='municipales2014', app_name='gpt2')),
    url(r'^cantonales2011/', include('gpt2.urls', namespace='cantonales2011', app_name='gpt2')),
    url(r'^legislatives2012/', include('gpt2.urls', namespace='legislatives2012', app_name='gpt2')),
    url(r'^legislatives2007/', include('gpt2.urls', namespace='legislatives2007', app_name='gpt2')),
    url(r'^initiatives/', include('gpt2.urls', namespace='initiatives', app_name='gpt2')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gpt2/urls.py
from django.conf.urls import patterns, url
from gpt2 import views
import gpt2.auth.views

urlpatterns = patterns (
    'gpt2.views',
    url(r'^/?$', views.index, name='index'),

    url(r'^login', gpt2.auth.views.login_form, name='login'),
    url(r'^logout', gpt2.auth.views.logout_form, name='logout'),

    url(r'^constituency/(?P<id>\d+)/?$', views.constituency_detail, name='constituency_detail'),
    url(r'^candidate/(?P<id>\d+)/?$', views.candidate_detail, name='candidate_detail'),

    url(r'^profile/(?P<id>\d+)$', views.view_profile, name='view_profile'),
    url(r'^profile/?$', views.view_profile, name='view_profile'),

    url(r'^candidates$', views.candidates_list, name='candidates_list'),
    url(r'^signatories$', views.signatories_list, name='signatories_list'),
    url(r'^constituencies$', views.constituencies_list, name='constituencies_list'),

    )

gpt2/models.py
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from utils import *
import os

def get_image_path(instance, filename):
    return 'photos/candidate_%s.png' % str(instance.id)

class Parti(models.Model):
    class Meta:
        db_table = 'parti'

    acronyme = models.CharField(max_length=16)
    nom_complet = models.CharField(max_length=64)
    description = models.TextField()

    def __unicode__(self):
        if self.acronyme:
            return "%s (%s)" % ( self.nom_complet, self.acronyme )
        else:
            return self.nom_complet



class Election(models.Model):
    class Meta:
        db_table = 'election'

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    label = models.CharField(max_length=255)
    status = models.IntegerField()
    url = models.CharField(max_length=255)
    pact_name = models.CharField(max_length=255)
    local_authority_type = models.CharField(max_length=255)



class Circonscription(models.Model):
    class Meta:
        db_table = 'circonscription'

    id = models.AutoField(primary_key=True)
    numero = models.IntegerField()
    description = models.TextField()
    code_postal = models.IntegerField()
    type = models.CharField(max_length=32)
    svg_id = models.CharField(max_length=16)

    def candidates_of_election(self, election_id):
        return self.candidates.filter(electioncandidatelink__election_id=election_id)



class Collectivite(models.Model):
    class Meta:
        db_table = 'collectivite'

    id = models.AutoField(primary_key=True)

    numero = models.IntegerField()
    description = models.TextField()
    type = models.CharField(max_length=32)
    svg_id = models.CharField(max_length=16)
    admin_info = models.TextField()
    order_num = models.IntegerField()



class CollectiviteLink(models.Model):
    class Meta:
        db_table = 'collectivite_link'

    id = models.AutoField(primary_key=True)
    child_type = models.TextField ()
    parent = models.OneToOneField ( Collectivite, 
                                    related_name = 'collectivite_link_parent')
    child = models.OneToOneField ( Circonscription, 
                                   related_name = 'collectivite_link_child' )



class ElectionConstituencyLink(models.Model):
    class Meta:
        db_table = 'election_constituency_link'

    election_constituency_link_id = models.AutoField(primary_key=True)
    constituency = models.ForeignKey ( Circonscription, related_name = 'election_constituency_link' )
    election = models.ForeignKey ( Election, related_name = 'election_constituency_link' )



class Candidat(models.Model):
    class Meta:
        db_table = 'candidat'

    parti = models.ForeignKey(Parti, related_name='candidat')
    civilite = models.CharField(max_length=255, null=True)
    prenom = models.CharField(max_length=255)
    nom = models.CharField(max_length=255)
    constituencies = models.ManyToManyField(Circonscription, through='ElectionCandidateLink', related_name='candidates')
    photo = models.ImageField(upload_to=get_image_path, blank=True, null=True)

    tel = models.CharField(max_length=255)
    fax = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    web = models.CharField(max_length=255)
    adresse = models.CharField(max_length=255)
    code_postal = models.CharField(max_length=20)
    ville = models.CharField(max_length=20)
    commentaire = models.CharField(max_length=255)
    commentaire_admin = models.CharField(max_length=255)


    # XXX howto add dynamic fields ?
    additional_position_in_list = models.IntegerField()
    additional_nom_liste = models.CharField(max_length=128)


    def constituencies_of_election(self, election_id):
        return self.constituencies.filter(election_candidate_link__election_id=election_id)

    def __unicode__(self):
        return "%s %s" % ( self.prenom, self.nom )

    def no_photo_url (self):
        if self.civilite == 'Mr':
            return 'images/candidate-no-photo-male.png'
        else:
            return 'images/candidate-no-photo-female.png'

class ElectionCandidateLink(models.Model):
    class Meta:
        db_table = 'election_candidate_link'

    election_candidate_link_id = models.AutoField(primary_key=True)
    candidate = models.ForeignKey(Candidat, related_name='election_candidate_link_c')
    constituency = models.ForeignKey(Circonscription, related_name='election_candidate_link')

    election = models.ForeignKey(Election, related_name='election_candidate_link')
    finalist = models.BooleanField(default=None)
    elected = models.BooleanField(default=None)

    votes_1st_ballot = models.FloatField()
    votes_2nd_ballot = models.FloatField()

    decision = models.CharField(max_length=20)



class Volontaire(models.Model):
    class Meta:
        db_table = 'volontaire'

    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, default=None, on_delete=models.CASCADE)
    login = models.CharField(max_length=255)
    passwd = models.CharField(max_length=255)

    photo = models.ImageField(upload_to=get_image_path, blank=True, null=True)
    prenom = models.CharField(max_length=255)
    nom = models.CharField(max_length=255)

    email = models.CharField(max_length=255)
    email_visible = models.BooleanField(default=None)
    email_valide = models.BooleanField(default=None)
    cle = models.CharField(max_length=41)

    code_postal = models.CharField(max_length=10)
    ville = models.CharField(max_length=255)
    tel = models.CharField(max_length=20)
    commentaire = models.CharField(max_length=255)

    def __unicode__(self):
        return "%s %s" % ( self.prenom, self.nom )


class Responsabilite(models.Model):
    class Meta:
        db_table = 'responsabilite'

    id = models.AutoField(primary_key=True)

    volontaire = models.ForeignKey(Volontaire,related_name='responsabilites')

    type = models.ForeignKey(ContentType, db_column='type')
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('type', 'object_id')

    validation = models.BooleanField()
    auteur_validation = models.CharField(max_length=20)
    date_validation = models.DateField()

    election = models.ForeignKey(Election)

gpt2/views.py
from django.conf import settings
from django.db.models import Q, Count
from django.http import HttpResponse, Http404
from django.contrib.auth.decorators import login_required
from django_tables2 import RequestConfig

from gpt2.models import *
from gpt2.tables import *
from gpt2.utils import *



def home ( request ):
    return gpt2_render_to_response ( request, 'home.html', { 'elections': Election.objects.all() } )


def index ( request ):
    eid = get_election_id_from_request ( request )

    count = ElectionCandidateLink.objects.filter ( Q(election_id = eid),
                                                   ( Q(decision = 'signe') | 
                                                     Q(decision = 'signe-valide' ) ) ).count

    parties = Parti.objects \
        .filter ( Q ( candidat__election_candidate_link_c__election_id = eid ), 
                  ( Q ( candidat__election_candidate_link_c__decision = 'signe-valide' ) | 
                    Q ( candidat__election_candidate_link_c__decision = 'signe') ) ) \
                    .annotate ( count = Count ( 'id' ) ) \
                    .order_by ( '-count' )

    return gpt2_render_to_response(request, 'index.html', { 'count' : count, 'parties' : parties } )


def view_profile(request, id = None):
    if id is None:
        id = request.user.id

    # XXX Dangerous, check I am admin
    volontaire = get_object_or_404(Volontaire, pk=id)

    return gpt2_render_to_response ( 
        request, 'volontaire.html', { 'volontaire': volontaire } )


def candidate_detail(request, id):
    candidat = get_object_or_404(Candidat, pk=id)

    return gpt2_render_to_response ( 
        request, 'candidat.html', { 'candidat': candidat } )


def constituencies_list ( request ):
    election = get_election_from_request ( request )

    constituencies = Circonscription.objects \
        .filter ( election_constituency_link__election_id = election.id ) \
        .filter ( collectivite_link_child__parent__type = election.local_authority_type ) \
        .order_by ( 'collectivite_link_child__parent__order_num', 
                    'collectivite_link_child__parent__numero', 
                    'collectivite_link_child__parent__description' ) \
        .prefetch_related ( 'collectivite_link_child__parent' )
                    
    return gpt2_render_to_response ( request, 'constituencies.html', 
                                     { 'constituencies': constituencies } )


def constituency_detail(request, id):
    eid = get_election_id_from_request ( request )
    the_constituency = get_object_or_404(Circonscription, pk=id)

    candidates = the_constituency.election_candidate_link \
        . filter ( election_id = eid ) \
        . order_by ( '-votes_1st_ballot', 'candidate__additional_nom_liste', 'candidate__additional_position_in_list', 'candidate__nom', 'candidate__prenom' ) \
        . prefetch_related ( 'candidate', 'candidate__parti' )

    finalists = the_constituency.election_candidate_link \
        . filter ( election_id = eid, finalist = 1 ) \
        . order_by ( '-elected', '-votes_2nd_ballot',  'candidate__additional_nom_liste', 'candidate__additional_position_in_list', 'candidate__nom', 'candidate__prenom' , '-votes_1st_ballot' ) \
        . prefetch_related ( 'candidate', 'candidate__parti' )

    other_elections = ElectionConstituencyLink.objects \
        .filter ( constituency = the_constituency ) \
        .exclude ( election_id = eid )
                                                                
    return gpt2_render_to_response ( request, 'constituency.html', 
                                     { 'constituency': the_constituency, 
                                       'candidates': candidates,
                                       'finalists': finalists,
                                       'other_elections': other_elections,
                                       'election_id': eid })


def signatories_list(request):
    request.GET = request.GET.copy ()
    request.GET [ 'signatories' ] = 1
    return candidates_list ( request )


def candidates_list(request):
    e = get_election_from_request ( request )
    cdt = Candidat.objects \
        . filter ( Q(election_candidate_link_c__election_id = e.id ) ) \
        . order_by ( 'nom', 'prenom' )
                         
    title = 'Candidats'

    if request.GET.has_key ( 'signatories' ):
        cdt = cdt . filter ( Q(election_candidate_link_c__decision = 'signe') | 
                             Q(election_candidate_link_c__decision = 'signe-valide' ) )
        title = 'Signatories'

    if request.GET.has_key ( 'party' ):
        cdt = cdt . filter ( parti_id = request.GET [ 'party' ] )
        title = '%s for %s' % ( title, Parti.objects.get(pk=request.GET [ 'party' ]) )

    cdt = cdt . distinct ( ) . prefetch_related ( 'parti' )

    table = CandidateTable(cdt, election=e)
    RequestConfig(request).configure(table)
                                                                
    return gpt2_render_to_response ( request, 'candidates.html', 
                                     { 'candidates': table,
                                       'title': title,
                                       'election_id': e.id } )

gpt2/templates/base.html
{% load staticfiles %}
{% load gpt2_extras %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.sandstone.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/gpt2.css' %}" />
    <link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" />
    <title>{% block title %}GPT2 powered website{% endblock %}</title>
  </head>

  <body>

    <div id="sidebar">
      {% block sidebar %}
      <nav class="navbar navbar-default navbar-default-top" role="navigation">
	<div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
	    {% if election %}
	    <a class="navbar-brand" href="{% url election.name|addstr:':index' %}">{% block thetitle %}GPT2{% endblock thetitle %}</a>
	    {% else %}
	    <a class="navbar-brand" href="#">GPT2</a>
	    {% endif %}
          </div>
          <div class="navbar-collapse navbar-right hidden-xs">
            <ul class="nav navbar-nav">
	      {% if user.is_authenticated %}
	      <li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
		  {% if user.volontaire.photo %}<img src="{{user.volontaire.photo.url}}" style="max-width:24px;max-height:24px;float:left;vertical-align:bottom;margin-right:1em;" />{% endif %} {{user.volontaire.prenom}} {{user.volontaire.nom}} <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li>
		    {% if election %}
                    <a href="{% url election.name|addstr:':view_profile' %}"><i class="fa fa-user"></i> View profile</a>
                    <a href="{% url election.name|addstr:':logout' %}"><i class="fa fa-sign-out"></i> Log Out</a>
		    {% else %}
                    <a href="{% url 'gpt2:logout' %}"><i class="icon fa fa-sign-out"></i> Log Out</a>
		    {% endif %}
                  </li>
		</ul>
	      </li>
	      {% else %}
	      {% if election %}
	      <li><a href="{% url election.name|addstr:':login' %}"><i class="fa fa-sign-in"></i> Sign in</a></li>
	      {% else %}
	      <li><a href="{% url 'gpt2:login' %}">Login</a></li>
	      {% endif %}
	      {% endif %}
	    </ul>
	  </div>
	</div>
      </nav>
      {% endblock %}
    </div>


    <div class="page-pre">

      <div class="page-post">

	<div class="page">

	  <div class="logo">
	    <div class="logo-top"><p><a href="http://campagnes.candidats.fr/departementales2015//"><b>{{election.label}}</b><br/>
	          Promouvoir &amp; d&eacute;fendre le logiciel
		  libre</a></p></div>
	    <div class="logo-bottom"></div>
	  </div> <!-- .logo -->
	  
	  <div class="menu">
	    {% if election %}
	    <ul><li><a class="menu-item"
		       href="{% url election.name|addstr:':index' %}">Accueil</a></li>
	      <li><a class="menu-item"
		     href="{% url election.name|addstr:':signatories_list' %}">Les
		  signataires</a></li>
	      <li><a class="menu-item"
		     href="{% url election.name|addstr:':constituencies_list' %}">Circonscriptions</a></li>
	      <li><a class="menu-item"
		     href="#">Statistiques</a></li>
	    </ul>
	    {% endif %}
	    
	  </div> <!-- .menu -->

	  <div class="content container-fluid">
	    {% block content %}{% endblock %}
	  </div> <!-- content -->
	</div>   <!-- page -->
      </div>      <!-- page-post -->
    </div>     <!-- page-pre -->
    
    <div class="footer" style="clear: both"->
      <p><a href="http://gna.org/projects/gpt/">GPT - Grassroot Platform
	  Technology</a> - Copyright 2007-2011 
	<a href="http://www.april.org/">April</a>.
	GPT est placé sous GNU Affero General Public License.</p>
    </div>
    
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

gpt2/templates/candidat.html
{% extends base_template %}
{% load gpt2_extras %}
{% load staticfiles %}

{% block title %}
{{candidat.prenom}} {{candidat.nom}}
{% endblock title %}

{% block content %}

<div class="page-header">
  <h1>{{candidat.prenom}} {{candidat.nom}}</h1>
</div>

<div class="row">
  <div class="col-sm-3">
    <div class="panel panel-default center">
      <div class="panel-heading">
	<h1 class="panel-title"><i class="fa fa-user"></i> {{candidat.prenom}} {{candidat.nom}}</h1>
      </div>
      <div class="panel-body img-responsive">
	{% if candidat.photo %}
	<img src="{{candidat.photo.url}}" 
	     class="img-responsive center-block" 
	     style="max-width:240px; max-height:240px;" />
	{% else %}
	<img src="{% static candidat.no_photo_url %}" 
	     class="img-responsive center-block" 
	     style="max-width:240px; max-height:240px;" />
	{% endif %}
	<p align="center"><strong><a href="{% url election.name|addstr:':candidates_list' %}?party={{candidat.parti.id}}">{{candidat.parti.nom_complet}}</a></strong></p>
      </div>
    </div>

  </div>
  
  <div class="col-sm-8 responsive-table">
    <h4>Contact</h4>

    <table class="table table-striped table-condensed">
      <tbody>
	<tr>
	  <td><i class="fa fa-home text-success"></i></td>
	  <td><strong>Adress:</strong></td>
	  <td>{% if candidat.adresse %}{{candidat.adresse}}<br/>{% endif %}
	    {{candidat.code_postal}} {{candidat.ville}}</td>
	</tr>
	<tr>
	  <td><i class="fa fa-phone text-success"></i></td>
	  <td><strong>Phone:</strong></td>
	  <td>{{candidat.telephone|default:'<span class="text-muted">None</span>'}}</td>
	</tr>
	<tr>
	  <td><i class="fa fa-fax text-success"></i></td>
	  <td><strong>Fax:</strong></td>
	  <td>{{candidat.fax|default:'<span class="text-muted">None</span>'}}</td>
	</tr>
	<tr>
	  <td><i class="fa fa-at text-success"></i></td>
	  <td><strong>E-mail:</strong></td>
	  <td>
	    {% if candidat.email %}
	    <a href="mailto:{{candidat.email|escape}}">{{candidat.email}}</a>
	    {% else %}
	    <span class="text-muted">None</span>
	    {% endif %}
	  </td>
	</tr>
      </tbody>
    </table>

  </div>

  <div class="col-sm-8">
    <ul class="list-group">
      <li class="list-group-item"><h4 class="list-group-item-heading">Candidate aux élections</h4></li>
      {% for c in candidat.election_candidate_link_c.all %}
      <li class="list-group-item"><a href="{% url c.election.name|addstr:':constituency_detail' c.constituency.id %}"> {%if c.elected %} <span class="label label-success pull-right"><b>Elected</b></span>{% endif %}{%if c.finalist and not c.elected %}<span class="label label-info pull-right"><b>Finalist</b></span>{% endif %}<b>{{c.election.label}}</b> - {{c.constituency.description}}</a></li>

      {% endfor %}
    </ul>
  </div>

</div>
{% endblock content %}

gpt2/templates/candidates.html
{% extends base_template %}
{% load gpt2_extras %}
{% load render_table from django_tables2 %}

{% block title %}
Candidates
{% endblock title %}

{% block content %}
<div class="page-header">
  <h1>{{title}}</h1>
</div>

{% render_table candidates %}
{% endblock content %}

gpt2/templates/constituencies.html
{% extends base_template %}
{% load gpt2_extras %}

{% block title %}
Constituencies
{% endblock title %}

{% block content %}
<h1>{{title}}</h1>


{% assign current '' %}
{% for c in constituencies %}
{% if current != c.collectivite_link_child.parent.description %}
  {% if current %}
</ul>
  {% endif %}
  {% assign current c.collectivite_link_child.parent.description %}
  <h2>{% if c.collectivite_link_child.parent.numero %}{{c.collectivite_link_child.parent.numero}} - {% endif %}{{current}}</h2>
<ul>
{% endif %}
<li><a href="{% url election.name|addstr:':constituency_detail' c.id %}">{{c.description}}</a></li>
{% endfor %}

{% endblock content %}

gpt2/templates/constituency.html
{% extends base_template %}
{% load staticfiles %}
{% load gpt2_extras %}

{% block title %}Candidats pour {{constituency.description}}{% endblock title %}

{% block content %}
<div class="page-header title">
  <h1>{{constituency.description}} <small>Results</small></h1>

</div>

{% for c in other_elections %}
<p>Also in: <a href="{% url c.election.name|addstr:':constituency_detail' c.constituency.id %}">{{c.election.label}}</a></p>
{% endfor %}

{% if election.status >= 2 and finalists %}

<h2>Second tour</h2>

<ul class="candidate-list">
{% for c in finalists %}
<li class="candidate-detail {%if c.elected %}candidate-elected {% endif %}candidate-party-{{c.candidate.parti.acronyme}}">
  <img src="{% if c.candidate.photo %}{{c.candidate.photo.url}}{% else %}{% static c.candidate.no_photo_url %}{% endif %}" class="candidate-photo" />
  <div class="candidate-container">
    {%if c.votes_2nd_ballot %}<span class="candidate-result">{{c.votes_2nd_ballot|stringformat:".2f"}}%</span>{% endif %}
    <a class="candidate-name" href="{% url 'gpt2:candidate_detail' c.candidate.id %}">{{c.candidate}}</a>
    <span class="candidate-party">{{c.candidate.parti}}</span>
    {%if c.candidate.additional_nom_liste %}<span class="candidate-list-name">{{c.candidate.additional_nom_liste}} | n°{{c.candidate.additional_position_in_list}}</span>{% endif %}
    {%if c.elected %}<span class="label label-success pull-right"><b>Elected</b></span>{% endif %}
  </div>
    {%if c.votes_2nd_ballot %}<span class="candidate-bar"
				    style="width:{{c.votes_2nd_ballot|stringformat:".2f"}}%">&nbsp;</span>{% else %}<span class="candidate-end"></span>{% endif %}
</li>
{% endfor %}
</ul>

{% endif %}


{% if election.status >= 1 %}

<h2>Premier tour</h2>

<ul class="candidate-list">
{% for c in candidates %}
<li class="candidate-detail {%if c.elected %}candidate-elected {% endif %}candidate-party-{{c.candidate.parti.acronyme}}">
  <img src="{% if c.candidate.photo %}{{c.candidate.photo.url}}{% else %}{% if c.candidate.civilite == 'Mrs' %}{% static 'images/candidate-no-photo-female.png' %}{% else %}{% static 'images/candidate-no-photo-male.png' %}{% endif %}{% endif %}" class="candidate-photo" />
  <div class="candidate-container">
    {%if c.votes_1st_ballot %}<span class="candidate-result pull-right">{{c.votes_1st_ballot|stringformat:".2f"}}%</span>{% endif %}
    <a class="candidate-name" href="{% url 'gpt2:candidate_detail' c.candidate.id %}">{{c.candidate}}</a>
    <span class="candidate-party">{{c.candidate.parti}}</span>
    {%if c.candidate.additional_nom_liste %}<span class="candidate-list-name">{{c.candidate.additional_nom_liste}} | n°{{c.candidate.additional_position_in_list}}</span>{% endif %}
    {%if c.elected %}<span class="label label-success pull-right"><b>Elected</b></span>{% endif %}
    {%if c.finalist and not c.elected %}<span class="label label-info pull-right"><b>Finalist</b></span>{% endif %}
  </div>
    {%if c.votes_1st_ballot %}<span class="candidate-bar"
				    style="width:{{c.votes_1st_ballot|stringformat:".2f"}}%">&nbsp;</span>{% else %}<span class="candidate-end"></span>{% endif %}
</li>
{% endfor %}
</ul>

{% endif %}


{% endblock content %}

gpt2/templates/home.html
{% extends base_template %}
{% load gpt2_extras %}

{% block title %}
GPT2 home
{% endblock title %}

{% block content %}

<ul class="list-group">
{% for election in elections.all %}
<li class="list-group-item"><a href="{% url election.name|addstr:':index'%}">{{election.label}}</a></li>
{% endfor %}
</ul>

{% endblock content %}

gpt2/templates/index.html
{% extends base_template %}

{% block title %}
Election summary
{% endblock title %}

{% block content %}

<div class="page-header">
  <h1>{{count}} signataires</h1>
</div>

<ul class="list-group">
{% for party in parties.all %}
<li class="list-group-item"><a href="{% url 'gpt2:signatories_list' %}?party={{party.id}}">{{party.nom_complet}}</a> <span class="badge">{{party.count}}</span></li>
{% endfor %}
</ul>

{% endblock content %}